# Generated by Django 4.2.5 on 2023-09-07 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Product name')),
                ('img', models.ImageField(upload_to='prod_images', verbose_name='Product image')),
                ('price', models.PositiveIntegerField(verbose_name='product price')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abc', to='main.category')),
            ],
        ),
    ]
